name: Format
on:
  pull_request:
jobs:
  format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - run: yarn install --check-files --frozen-lockfile --non-interactive
      - id: format
        run: |
          yarn format
          echo "::set-output name=status::$(git status --porcelain)"
      - if: steps.format.outputs.status != ''
        run: |
          git -c "user.name=${{ github.actor }}" -c "user.email=${{ github.actor }}@users.noreply.github.com" commit -a -m "bot: format"
          git push origin HEAD
